name: Publish to NPM

on:
  workflow_run:
    workflows: ["Build Go and Create GitHub Release"]
    types: [completed]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to npm
        run: pnpm publish --access public --no-git-checks
        working-directory: ./npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}